window.esdocSearchIndex = [
  [
    "tman-wrtc/lib/cache.js~cache",
    "class/lib/cache.js~Cache.html",
    "<span>Cache</span> <span class=\"search-result-import-path\">tman-wrtc/lib/cache.js</span>",
    "class"
  ],
  [
    "tman-wrtc/lib/entries/epv.js~epv",
    "class/lib/entries/epv.js~EPV.html",
    "<span>EPV</span> <span class=\"search-result-import-path\">tman-wrtc/lib/entries/epv.js</span>",
    "class"
  ],
  [
    "tman-wrtc/lib/exceptions/exjoin.js~exjoin",
    "class/lib/exceptions/exjoin.js~ExJoin.html",
    "<span>ExJoin</span> <span class=\"search-result-import-path\">tman-wrtc/lib/exceptions/exjoin.js</span>",
    "class"
  ],
  [
    "tman-wrtc/lib/exceptions/exmessage.js~exmessage",
    "class/lib/exceptions/exmessage.js~ExMessage.html",
    "<span>ExMessage</span> <span class=\"search-result-import-path\">tman-wrtc/lib/exceptions/exmessage.js</span>",
    "class"
  ],
  [
    "tman-wrtc/lib/exceptions/expeernotfound.js~expeernotfound",
    "class/lib/exceptions/expeernotfound.js~ExPeerNotFound.html",
    "<span>ExPeerNotFound</span> <span class=\"search-result-import-path\">tman-wrtc/lib/exceptions/expeernotfound.js</span>",
    "class"
  ],
  [
    "tman-wrtc/lib/messages/mgivedescriptor.js~mgivedescriptor",
    "class/lib/messages/mgivedescriptor.js~MGiveDescriptor.html",
    "<span>MGiveDescriptor</span> <span class=\"search-result-import-path\">tman-wrtc/lib/messages/mgivedescriptor.js</span>",
    "class"
  ],
  [
    "tman-wrtc/lib/messages/mjoin.js~mjoin",
    "class/lib/messages/mjoin.js~MJoin.html",
    "<span>MJoin</span> <span class=\"search-result-import-path\">tman-wrtc/lib/messages/mjoin.js</span>",
    "class"
  ],
  [
    "tman-wrtc/lib/messages/mrequestdescriptor.js~mrequestdescriptor",
    "class/lib/messages/mrequestdescriptor.js~MRequestDescriptor.html",
    "<span>MRequestDescriptor</span> <span class=\"search-result-import-path\">tman-wrtc/lib/messages/mrequestdescriptor.js</span>",
    "class"
  ],
  [
    "tman-wrtc/lib/messages/mrequire.js~mrequire",
    "class/lib/messages/mrequire.js~MRequire.html",
    "<span>MRequire</span> <span class=\"search-result-import-path\">tman-wrtc/lib/messages/mrequire.js</span>",
    "class"
  ],
  [
    "tman-wrtc/lib/messages/msuggest.js~msuggest",
    "class/lib/messages/msuggest.js~MSuggest.html",
    "<span>MSuggest</span> <span class=\"search-result-import-path\">tman-wrtc/lib/messages/msuggest.js</span>",
    "class"
  ],
  [
    "tman-wrtc/lib/messages/msuggestback.js~msuggestback",
    "class/lib/messages/msuggestback.js~MSuggestBack.html",
    "<span>MSuggestBack</span> <span class=\"search-result-import-path\">tman-wrtc/lib/messages/msuggestback.js</span>",
    "class"
  ],
  [
    "tman-wrtc~n2n",
    "variable/index.html#static-variable-N2N",
    "<span>N2N</span> <span class=\"search-result-import-path\">tman-wrtc</span>",
    "variable"
  ],
  [
    "tman-wrtc/lib/partialview.js~partialview",
    "class/lib/partialview.js~PartialView.html",
    "<span>PartialView</span> <span class=\"search-result-import-path\">tman-wrtc/lib/partialview.js</span>",
    "class"
  ],
  [
    "tman-wrtc~tman",
    "class/lib/tman.js~TMan.html",
    "<span>TMan</span> <span class=\"search-result-import-path\">tman-wrtc</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "lib/cache.js",
    "file/lib/cache.js.html",
    "lib/cache.js",
    "file"
  ],
  [
    "lib/cache.js~cache#add",
    "class/lib/cache.js~Cache.html#instance-method-add",
    "lib/cache.js~Cache#add",
    "method"
  ],
  [
    "lib/cache.js~cache#constructor",
    "class/lib/cache.js~Cache.html#instance-constructor-constructor",
    "lib/cache.js~Cache#constructor",
    "method"
  ],
  [
    "lib/cache.js~cache#timeout",
    "class/lib/cache.js~Cache.html#instance-member-timeout",
    "lib/cache.js~Cache#timeout",
    "member"
  ],
  [
    "lib/entries/epv.js",
    "file/lib/entries/epv.js.html",
    "lib/entries/epv.js",
    "file"
  ],
  [
    "lib/entries/epv.js~epv#add",
    "class/lib/entries/epv.js~EPV.html#instance-method-add",
    "lib/entries/epv.js~EPV#add",
    "method"
  ],
  [
    "lib/entries/epv.js~epv#ages",
    "class/lib/entries/epv.js~EPV.html#instance-member-ages",
    "lib/entries/epv.js~EPV#ages",
    "member"
  ],
  [
    "lib/entries/epv.js~epv#constructor",
    "class/lib/entries/epv.js~EPV.html#instance-constructor-constructor",
    "lib/entries/epv.js~EPV#constructor",
    "method"
  ],
  [
    "lib/entries/epv.js~epv#count",
    "class/lib/entries/epv.js~EPV.html#instance-get-count",
    "lib/entries/epv.js~EPV#count",
    "member"
  ],
  [
    "lib/entries/epv.js~epv#descriptor",
    "class/lib/entries/epv.js~EPV.html#instance-member-descriptor",
    "lib/entries/epv.js~EPV#descriptor",
    "member"
  ],
  [
    "lib/entries/epv.js~epv#increment",
    "class/lib/entries/epv.js~EPV.html#instance-method-increment",
    "lib/entries/epv.js~EPV#increment",
    "method"
  ],
  [
    "lib/entries/epv.js~epv#oldest",
    "class/lib/entries/epv.js~EPV.html#instance-get-oldest",
    "lib/entries/epv.js~EPV#oldest",
    "member"
  ],
  [
    "lib/entries/epv.js~epv#peer",
    "class/lib/entries/epv.js~EPV.html#instance-member-peer",
    "lib/entries/epv.js~EPV#peer",
    "member"
  ],
  [
    "lib/entries/epv.js~epv#removeoldest",
    "class/lib/entries/epv.js~EPV.html#instance-method-removeOldest",
    "lib/entries/epv.js~EPV#removeOldest",
    "method"
  ],
  [
    "lib/entries/epv.js~epv#removeyoungest",
    "class/lib/entries/epv.js~EPV.html#instance-method-removeYoungest",
    "lib/entries/epv.js~EPV#removeYoungest",
    "method"
  ],
  [
    "lib/entries/epv.js~epv#update",
    "class/lib/entries/epv.js~EPV.html#instance-method-update",
    "lib/entries/epv.js~EPV#update",
    "method"
  ],
  [
    "lib/exceptions/exinterface.js",
    "file/lib/exceptions/exinterface.js.html",
    "lib/exceptions/exinterface.js",
    "file"
  ],
  [
    "lib/exceptions/exjoin.js",
    "file/lib/exceptions/exjoin.js.html",
    "lib/exceptions/exjoin.js",
    "file"
  ],
  [
    "lib/exceptions/exjoin.js~exjoin#constructor",
    "class/lib/exceptions/exjoin.js~ExJoin.html#instance-constructor-constructor",
    "lib/exceptions/exjoin.js~ExJoin#constructor",
    "method"
  ],
  [
    "lib/exceptions/exjoin.js~exjoin#message",
    "class/lib/exceptions/exjoin.js~ExJoin.html#instance-member-message",
    "lib/exceptions/exjoin.js~ExJoin#message",
    "member"
  ],
  [
    "lib/exceptions/exjoin.js~exjoin#source",
    "class/lib/exceptions/exjoin.js~ExJoin.html#instance-member-source",
    "lib/exceptions/exjoin.js~ExJoin#source",
    "member"
  ],
  [
    "lib/exceptions/exmessage.js",
    "file/lib/exceptions/exmessage.js.html",
    "lib/exceptions/exmessage.js",
    "file"
  ],
  [
    "lib/exceptions/exmessage.js~exmessage#constructor",
    "class/lib/exceptions/exmessage.js~ExMessage.html#instance-constructor-constructor",
    "lib/exceptions/exmessage.js~ExMessage#constructor",
    "method"
  ],
  [
    "lib/exceptions/exmessage.js~exmessage#message",
    "class/lib/exceptions/exmessage.js~ExMessage.html#instance-member-message",
    "lib/exceptions/exmessage.js~ExMessage#message",
    "member"
  ],
  [
    "lib/exceptions/exmessage.js~exmessage#reason",
    "class/lib/exceptions/exmessage.js~ExMessage.html#instance-member-reason",
    "lib/exceptions/exmessage.js~ExMessage#reason",
    "member"
  ],
  [
    "lib/exceptions/exmessage.js~exmessage#source",
    "class/lib/exceptions/exmessage.js~ExMessage.html#instance-member-source",
    "lib/exceptions/exmessage.js~ExMessage#source",
    "member"
  ],
  [
    "lib/exceptions/expeernotfound.js",
    "file/lib/exceptions/expeernotfound.js.html",
    "lib/exceptions/expeernotfound.js",
    "file"
  ],
  [
    "lib/exceptions/expeernotfound.js~expeernotfound#constructor",
    "class/lib/exceptions/expeernotfound.js~ExPeerNotFound.html#instance-constructor-constructor",
    "lib/exceptions/expeernotfound.js~ExPeerNotFound#constructor",
    "method"
  ],
  [
    "lib/exceptions/expeernotfound.js~expeernotfound#peer",
    "class/lib/exceptions/expeernotfound.js~ExPeerNotFound.html#instance-member-peer",
    "lib/exceptions/expeernotfound.js~ExPeerNotFound#peer",
    "member"
  ],
  [
    "lib/exceptions/expeernotfound.js~expeernotfound#source",
    "class/lib/exceptions/expeernotfound.js~ExPeerNotFound.html#instance-member-source",
    "lib/exceptions/expeernotfound.js~ExPeerNotFound#source",
    "member"
  ],
  [
    "lib/messages/mgivedescriptor.js",
    "file/lib/messages/mgivedescriptor.js.html",
    "lib/messages/mgivedescriptor.js",
    "file"
  ],
  [
    "lib/messages/mgivedescriptor.js~mgivedescriptor#constructor",
    "class/lib/messages/mgivedescriptor.js~MGiveDescriptor.html#instance-constructor-constructor",
    "lib/messages/mgivedescriptor.js~MGiveDescriptor#constructor",
    "method"
  ],
  [
    "lib/messages/mgivedescriptor.js~mgivedescriptor#descriptor",
    "class/lib/messages/mgivedescriptor.js~MGiveDescriptor.html#instance-member-descriptor",
    "lib/messages/mgivedescriptor.js~MGiveDescriptor#descriptor",
    "member"
  ],
  [
    "lib/messages/mgivedescriptor.js~mgivedescriptor#peer",
    "class/lib/messages/mgivedescriptor.js~MGiveDescriptor.html#instance-member-peer",
    "lib/messages/mgivedescriptor.js~MGiveDescriptor#peer",
    "member"
  ],
  [
    "lib/messages/mgivedescriptor.js~mgivedescriptor#type",
    "class/lib/messages/mgivedescriptor.js~MGiveDescriptor.html#instance-member-type",
    "lib/messages/mgivedescriptor.js~MGiveDescriptor#type",
    "member"
  ],
  [
    "lib/messages/mjoin.js",
    "file/lib/messages/mjoin.js.html",
    "lib/messages/mjoin.js",
    "file"
  ],
  [
    "lib/messages/mjoin.js~mjoin#constructor",
    "class/lib/messages/mjoin.js~MJoin.html#instance-constructor-constructor",
    "lib/messages/mjoin.js~MJoin#constructor",
    "method"
  ],
  [
    "lib/messages/mjoin.js~mjoin#descriptor",
    "class/lib/messages/mjoin.js~MJoin.html#instance-member-descriptor",
    "lib/messages/mjoin.js~MJoin#descriptor",
    "member"
  ],
  [
    "lib/messages/mjoin.js~mjoin#peer",
    "class/lib/messages/mjoin.js~MJoin.html#instance-member-peer",
    "lib/messages/mjoin.js~MJoin#peer",
    "member"
  ],
  [
    "lib/messages/mjoin.js~mjoin#type",
    "class/lib/messages/mjoin.js~MJoin.html#instance-member-type",
    "lib/messages/mjoin.js~MJoin#type",
    "member"
  ],
  [
    "lib/messages/mrequestdescriptor.js",
    "file/lib/messages/mrequestdescriptor.js.html",
    "lib/messages/mrequestdescriptor.js",
    "file"
  ],
  [
    "lib/messages/mrequestdescriptor.js~mrequestdescriptor#constructor",
    "class/lib/messages/mrequestdescriptor.js~MRequestDescriptor.html#instance-constructor-constructor",
    "lib/messages/mrequestdescriptor.js~MRequestDescriptor#constructor",
    "method"
  ],
  [
    "lib/messages/mrequestdescriptor.js~mrequestdescriptor#type",
    "class/lib/messages/mrequestdescriptor.js~MRequestDescriptor.html#instance-member-type",
    "lib/messages/mrequestdescriptor.js~MRequestDescriptor#type",
    "member"
  ],
  [
    "lib/messages/mrequire.js",
    "file/lib/messages/mrequire.js.html",
    "lib/messages/mrequire.js",
    "file"
  ],
  [
    "lib/messages/mrequire.js~mrequire#constructor",
    "class/lib/messages/mrequire.js~MRequire.html#instance-constructor-constructor",
    "lib/messages/mrequire.js~MRequire#constructor",
    "method"
  ],
  [
    "lib/messages/mrequire.js~mrequire#peers",
    "class/lib/messages/mrequire.js~MRequire.html#instance-member-peers",
    "lib/messages/mrequire.js~MRequire#peers",
    "member"
  ],
  [
    "lib/messages/mrequire.js~mrequire#type",
    "class/lib/messages/mrequire.js~MRequire.html#instance-member-type",
    "lib/messages/mrequire.js~MRequire#type",
    "member"
  ],
  [
    "lib/messages/msuggest.js",
    "file/lib/messages/msuggest.js.html",
    "lib/messages/msuggest.js",
    "file"
  ],
  [
    "lib/messages/msuggest.js~msuggest#constructor",
    "class/lib/messages/msuggest.js~MSuggest.html#instance-constructor-constructor",
    "lib/messages/msuggest.js~MSuggest#constructor",
    "method"
  ],
  [
    "lib/messages/msuggest.js~msuggest#descriptor",
    "class/lib/messages/msuggest.js~MSuggest.html#instance-member-descriptor",
    "lib/messages/msuggest.js~MSuggest#descriptor",
    "member"
  ],
  [
    "lib/messages/msuggest.js~msuggest#peer",
    "class/lib/messages/msuggest.js~MSuggest.html#instance-member-peer",
    "lib/messages/msuggest.js~MSuggest#peer",
    "member"
  ],
  [
    "lib/messages/msuggest.js~msuggest#sample",
    "class/lib/messages/msuggest.js~MSuggest.html#instance-member-sample",
    "lib/messages/msuggest.js~MSuggest#sample",
    "member"
  ],
  [
    "lib/messages/msuggest.js~msuggest#type",
    "class/lib/messages/msuggest.js~MSuggest.html#instance-member-type",
    "lib/messages/msuggest.js~MSuggest#type",
    "member"
  ],
  [
    "lib/messages/msuggestback.js",
    "file/lib/messages/msuggestback.js.html",
    "lib/messages/msuggestback.js",
    "file"
  ],
  [
    "lib/messages/msuggestback.js~msuggestback#constructor",
    "class/lib/messages/msuggestback.js~MSuggestBack.html#instance-constructor-constructor",
    "lib/messages/msuggestback.js~MSuggestBack#constructor",
    "method"
  ],
  [
    "lib/messages/msuggestback.js~msuggestback#sample",
    "class/lib/messages/msuggestback.js~MSuggestBack.html#instance-member-sample",
    "lib/messages/msuggestback.js~MSuggestBack#sample",
    "member"
  ],
  [
    "lib/messages/msuggestback.js~msuggestback#type",
    "class/lib/messages/msuggestback.js~MSuggestBack.html#instance-member-type",
    "lib/messages/msuggestback.js~MSuggestBack#type",
    "member"
  ],
  [
    "lib/partialview.js",
    "file/lib/partialview.js.html",
    "lib/partialview.js",
    "file"
  ],
  [
    "lib/partialview.js~partialview#addneighbor",
    "class/lib/partialview.js~PartialView.html#instance-method-addNeighbor",
    "lib/partialview.js~PartialView#addNeighbor",
    "method"
  ],
  [
    "lib/partialview.js~partialview#constructor",
    "class/lib/partialview.js~PartialView.html#instance-constructor-constructor",
    "lib/partialview.js~PartialView#constructor",
    "method"
  ],
  [
    "lib/partialview.js~partialview#getdescriptor",
    "class/lib/partialview.js~PartialView.html#instance-method-getDescriptor",
    "lib/partialview.js~PartialView#getDescriptor",
    "method"
  ],
  [
    "lib/partialview.js~partialview#increment",
    "class/lib/partialview.js~PartialView.html#instance-method-increment",
    "lib/partialview.js~PartialView#increment",
    "method"
  ],
  [
    "lib/partialview.js~partialview#leastfrequent",
    "class/lib/partialview.js~PartialView.html#instance-get-leastFrequent",
    "lib/partialview.js~PartialView#leastFrequent",
    "member"
  ],
  [
    "lib/partialview.js~partialview#oldest",
    "class/lib/partialview.js~PartialView.html#instance-get-oldest",
    "lib/partialview.js~PartialView#oldest",
    "member"
  ],
  [
    "lib/partialview.js~partialview#removeallneighbor",
    "class/lib/partialview.js~PartialView.html#instance-method-removeAllNeighbor",
    "lib/partialview.js~PartialView#removeAllNeighbor",
    "method"
  ],
  [
    "lib/partialview.js~partialview#removeoldest",
    "class/lib/partialview.js~PartialView.html#instance-method-removeOldest",
    "lib/partialview.js~PartialView#removeOldest",
    "method"
  ],
  [
    "lib/partialview.js~partialview#updateneighbor",
    "class/lib/partialview.js~PartialView.html#instance-method-updateNeighbor",
    "lib/partialview.js~PartialView#updateNeighbor",
    "method"
  ],
  [
    "lib/tman.js",
    "file/lib/tman.js.html",
    "lib/tman.js",
    "file"
  ],
  [
    "lib/tman.js~tman#_close",
    "class/lib/tman.js~TMan.html#instance-method-_close",
    "lib/tman.js~TMan#_close",
    "method"
  ],
  [
    "lib/tman.js~tman#_exchange",
    "class/lib/tman.js~TMan.html#instance-method-_exchange",
    "lib/tman.js~TMan#_exchange",
    "method"
  ],
  [
    "lib/tman.js~tman#_getsample",
    "class/lib/tman.js~TMan.html#instance-method-_getSample",
    "lib/tman.js~TMan#_getSample",
    "method"
  ],
  [
    "lib/tman.js~tman#_keep",
    "class/lib/tman.js~TMan.html#instance-method-_keep",
    "lib/tman.js~TMan#_keep",
    "method"
  ],
  [
    "lib/tman.js~tman#_onarcdown",
    "class/lib/tman.js~TMan.html#instance-method-_onArcDown",
    "lib/tman.js~TMan#_onArcDown",
    "method"
  ],
  [
    "lib/tman.js~tman#_onexchange",
    "class/lib/tman.js~TMan.html#instance-method-_onExchange",
    "lib/tman.js~TMan#_onExchange",
    "method"
  ],
  [
    "lib/tman.js~tman#_onexchangeback",
    "class/lib/tman.js~TMan.html#instance-method-_onExchangeBack",
    "lib/tman.js~TMan#_onExchangeBack",
    "method"
  ],
  [
    "lib/tman.js~tman#_onjoin",
    "class/lib/tman.js~TMan.html#instance-method-_onJoin",
    "lib/tman.js~TMan#_onJoin",
    "method"
  ],
  [
    "lib/tman.js~tman#_onpeerdown",
    "class/lib/tman.js~TMan.html#instance-method-_onPeerDown",
    "lib/tman.js~TMan#_onPeerDown",
    "method"
  ],
  [
    "lib/tman.js~tman#_onrequestdescriptor",
    "class/lib/tman.js~TMan.html#instance-method-_onRequestDescriptor",
    "lib/tman.js~TMan#_onRequestDescriptor",
    "method"
  ],
  [
    "lib/tman.js~tman#_onrequire",
    "class/lib/tman.js~TMan.html#instance-method-_onRequire",
    "lib/tman.js~TMan#_onRequire",
    "method"
  ],
  [
    "lib/tman.js~tman#_open",
    "class/lib/tman.js~TMan.html#instance-method-_open",
    "lib/tman.js~TMan#_open",
    "method"
  ],
  [
    "lib/tman.js~tman#_partialviewsize",
    "class/lib/tman.js~TMan.html#instance-method-_partialViewSize",
    "lib/tman.js~TMan#_partialViewSize",
    "method"
  ],
  [
    "lib/tman.js~tman#_receive",
    "class/lib/tman.js~TMan.html#instance-method-_receive",
    "lib/tman.js~TMan#_receive",
    "method"
  ],
  [
    "lib/tman.js~tman#_requestdescriptor",
    "class/lib/tman.js~TMan.html#instance-method-_requestDescriptor",
    "lib/tman.js~TMan#_requestDescriptor",
    "method"
  ],
  [
    "lib/tman.js~tman#_samplesize",
    "class/lib/tman.js~TMan.html#instance-method-_sampleSize",
    "lib/tman.js~TMan#_sampleSize",
    "method"
  ],
  [
    "lib/tman.js~tman#_start",
    "class/lib/tman.js~TMan.html#instance-method-_start",
    "lib/tman.js~TMan#_start",
    "method"
  ],
  [
    "lib/tman.js~tman#_stop",
    "class/lib/tman.js~TMan.html#instance-method-_stop",
    "lib/tman.js~TMan#_stop",
    "method"
  ],
  [
    "lib/tman.js~tman#_updatestate",
    "class/lib/tman.js~TMan.html#instance-method-_updateState",
    "lib/tman.js~TMan#_updateState",
    "method"
  ],
  [
    "lib/tman.js~tman#cache",
    "class/lib/tman.js~TMan.html#instance-member-cache",
    "lib/tman.js~TMan#cache",
    "member"
  ],
  [
    "lib/tman.js~tman#constructor",
    "class/lib/tman.js~TMan.html#instance-constructor-constructor",
    "lib/tman.js~TMan#constructor",
    "method"
  ],
  [
    "lib/tman.js~tman#getpeers",
    "class/lib/tman.js~TMan.html#instance-method-getPeers",
    "lib/tman.js~TMan#getPeers",
    "method"
  ],
  [
    "lib/tman.js~tman#join",
    "class/lib/tman.js~TMan.html#instance-method-join",
    "lib/tman.js~TMan#join",
    "method"
  ],
  [
    "lib/tman.js~tman#parent",
    "class/lib/tman.js~TMan.html#instance-member-parent",
    "lib/tman.js~TMan#parent",
    "member"
  ],
  [
    "lib/tman.js~tman#partialview",
    "class/lib/tman.js~TMan.html#instance-member-partialView",
    "lib/tman.js~TMan#partialView",
    "member"
  ],
  [
    "lib/tman.js~tman#periodic",
    "class/lib/tman.js~TMan.html#instance-member-periodic",
    "lib/tman.js~TMan#periodic",
    "member"
  ],
  [
    "lib/tman.js~tman#state",
    "class/lib/tman.js~TMan.html#instance-member-state",
    "lib/tman.js~TMan#state",
    "member"
  ],
  [
    "lib/tman.js~tman#unicast",
    "class/lib/tman.js~TMan.html#instance-member-unicast",
    "lib/tman.js~TMan#unicast",
    "member"
  ]
]